scripts/dtc/pylibfdt/libfdt.i_shipped: Use SWIG_AppendOutput
This is a backport from
https://github.com/u-boot/u-boot/commit/a63456b9191fa

Original commit message:
---
Swig has changed language specific AppendOutput functions. The helper
macro SWIG_AppendOutput remains unchanged. Use that instead of
SWIG_Python_AppendOutput, which would require an extra parameter since
swig 4.3.0.

/home/flk/poky/build-test/tmp/work/qemux86_64-poky-linux/u-boot/2024.10/git/arch/x86/cpu/u-boot-64.lds
| scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_next_node’:
| scripts/dtc/pylibfdt/libfdt_wrap.c:5581:17: error: too few arguments
to function ‘SWIG_Python_AppendOutput’
|  5581 |     resultobj = SWIG_Python_AppendOutput(resultobj, val);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Reported-by: Rudi Heitbaum <rudi@heitbaum.com>
Link: dgibson/dtc#154
---

Signed-off-by: Matthias Proske <matthias.p@variscite.com>